name: simple-photo-meta
base: core22
version: '0.1.0'
summary: Simple Photo Meta Editor
description: |
  A local GUI tool for editing IPTC metadata on photos (built with PySide6 & Exiv2).

grade: stable
confinement: strict

apps:
  simple-photo-meta:
    command: bin/simple-photo-meta
    plugs:
      - home
      - removable-media
      - x11
      - wayland
      - opengl
parts:
  simple-photo-meta:
    plugin: python
    source: .
    python-packages:
      - .  # the app
      - Pillow==11.2.1
      - PySide6==6.9.0
      - pyside6-addons==6.9.0
      - pyside6-essentials==6.9.0
      - shiboken6==6.9.0
    stage-packages:
      - exiv2
      # Qt / OpenGL support for PySide6
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxkbcommon0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-xinerama0
      - libfontconfig1
      - libpulse0
      - libatomic1
      - libxcomposite1
      - libxdamage1
      - libxi6
      - libxrandr2
      - libxrender1
      - libxtst6
      - libasound2
      - libnspr4
      - libnss3
      - libxkbfile1
      - libxslt1.1
      - libwayland-cursor0
      - libwayland-egl1
      - libxcb-cursor0
      - libxcb-shape0
      - libxcb-xkb1
      - libxkbcommon-x11-0
      - libcups2
      - libatk1.0-0
      - libcairo2
      - libcairo-gobject2
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libspeechd2
      - libmysqlclient21
      - libodbc2
      - libpq5