exif_writable_tags = [
    {
        "tag": "Artist",
        "name": "Artist",
        "description": "Name of the photographer or creator.",
        "multi_valued": False,
    },
    {
        "tag": "Copyright",
        "name": "Copyright",
        "description": "Copyright notice for the image.",
        "multi_valued": False,
    },
    {
        "tag": "ImageDescription",
        "name": "Image Description",
        "description": "A description of the image content.",
        "multi_valued": False,
    },
    {
        "tag": "UserComment",
        "name": "User Comment",
        "description": "User-defined comment or notes.",
        "multi_valued": False,
    },
    {
        "tag": "Make",
        "name": "Camera Make",
        "description": "Manufacturer of the camera.",
        "multi_valued": False,
    },
    {
        "tag": "Model",
        "name": "Camera Model",
        "description": "Model of the camera.",
        "multi_valued": False,
    },
    {
        "tag": "Software",
        "name": "Software",
        "description": "Software used to create or process the image.",
        "multi_valued": False,
    },
    {
        "tag": "DateTime",
        "name": "Date/Time",
        "description": "Date and time of image modification (YYYY:MM:DD HH:MM:SS).",
        "multi_valued": False,
    },
    {
        "tag": "DateTimeOriginal",
        "name": "Date/Time Original",
        "description": "Date and time when the photo was taken (YYYY:MM:DD HH:MM:SS).",
        "multi_valued": False,
    },
    {
        "tag": "DateTimeDigitized",
        "name": "Date/Time Digitized",
        "description": "Date and time when the image was digitized (YYYY:MM:DD HH:MM:SS).",
        "multi_valued": False,
    },
    {
        "tag": "Orientation",
        "name": "Orientation",
        "description": "Image orientation (1-8, where 1=normal, 3=180deg, 6=90deg CW, 8=90deg CCW).",
        "multi_valued": False,
    },
    {
        "tag": "XResolution",
        "name": "X Resolution",
        "description": "Horizontal resolution in pixels per unit.",
        "multi_valued": False,
    },
    {
        "tag": "YResolution",
        "name": "Y Resolution",
        "description": "Vertical resolution in pixels per unit.",
        "multi_valued": False,
    },
    {
        "tag": "ResolutionUnit",
        "name": "Resolution Unit",
        "description": "Unit for X/Y resolution (2=inches, 3=centimeters).",
        "multi_valued": False,
    },
    {
        "tag": "ExposureTime",
        "name": "Exposure Time",
        "description": "Exposure time in seconds (e.g., 1/125).",
        "multi_valued": False,
    },
    {
        "tag": "FNumber",
        "name": "F-Number",
        "description": "F-number/aperture (e.g., f/2.8).",
        "multi_valued": False,
    },
    {
        "tag": "ISO",
        "name": "ISO Speed",
        "description": "ISO speed rating.",
        "multi_valued": False,
    },
    {
        "tag": "ExposureProgram",
        "name": "Exposure Program",
        "description": "Exposure program mode (0=not defined, 1=manual, 2=normal, 3=aperture priority, 4=shutter priority, etc.).",
        "multi_valued": False,
    },
    {
        "tag": "ExposureBiasValue",
        "name": "Exposure Bias",
        "description": "Exposure bias/compensation value in EV.",
        "multi_valued": False,
    },
    {
        "tag": "MeteringMode",
        "name": "Metering Mode",
        "description": "Metering mode (0=unknown, 1=average, 2=center-weighted, 3=spot, 5=pattern, 6=partial).",
        "multi_valued": False,
    },
    {
        "tag": "Flash",
        "name": "Flash",
        "description": "Flash mode and status.",
        "multi_valued": False,
    },
    {
        "tag": "FocalLength",
        "name": "Focal Length",
        "description": "Focal length in mm.",
        "multi_valued": False,
    },
    {
        "tag": "FocalLengthIn35mmFilm",
        "name": "Focal Length (35mm)",
        "description": "Focal length in 35mm equivalent.",
        "multi_valued": False,
    },
    {
        "tag": "WhiteBalance",
        "name": "White Balance",
        "description": "White balance mode (0=auto, 1=manual).",
        "multi_valued": False,
    },
    {
        "tag": "DigitalZoomRatio",
        "name": "Digital Zoom",
        "description": "Digital zoom ratio.",
        "multi_valued": False,
    },
    {
        "tag": "SceneCaptureType",
        "name": "Scene Type",
        "description": "Type of scene (0=standard, 1=landscape, 2=portrait, 3=night).",
        "multi_valued": False,
    },
    {
        "tag": "Contrast",
        "name": "Contrast",
        "description": "Contrast processing (0=normal, 1=soft, 2=hard).",
        "multi_valued": False,
    },
    {
        "tag": "Saturation",
        "name": "Saturation",
        "description": "Saturation processing (0=normal, 1=low, 2=high).",
        "multi_valued": False,
    },
    {
        "tag": "Sharpness",
        "name": "Sharpness",
        "description": "Sharpness processing (0=normal, 1=soft, 2=hard).",
        "multi_valued": False,
    },
    {
        "tag": "LensModel",
        "name": "Lens Model",
        "description": "Lens model name.",
        "multi_valued": False,
    },
    {
        "tag": "LensMake",
        "name": "Lens Make",
        "description": "Lens manufacturer.",
        "multi_valued": False,
    },
    {
        "tag": "GPSLatitude",
        "name": "GPS Latitude",
        "description": "Latitude coordinate (e.g., 37.7749 or 37deg 46' 29.64\"N).",
        "multi_valued": False,
    },
    {
        "tag": "GPSLongitude",
        "name": "GPS Longitude",
        "description": "Longitude coordinate (e.g., -122.4194 or 122deg 25' 9.84\"W).",
        "multi_valued": False,
    },
    {
        "tag": "GPSAltitude",
        "name": "GPS Altitude",
        "description": "Altitude in meters above sea level.",
        "multi_valued": False,
    },
    {
        "tag": "GPSLatitudeRef",
        "name": "GPS Latitude Ref",
        "description": "Latitude reference (N or S).",
        "multi_valued": False,
    },
    {
        "tag": "GPSLongitudeRef",
        "name": "GPS Longitude Ref",
        "description": "Longitude reference (E or W).",
        "multi_valued": False,
    },
    {
        "tag": "GPSAltitudeRef",
        "name": "GPS Altitude Ref",
        "description": "Altitude reference (0=above sea level, 1=below sea level).",
        "multi_valued": False,
    },
    {
        "tag": "GPSSpeed",
        "name": "GPS Speed",
        "description": "Speed of GPS receiver movement.",
        "multi_valued": False,
    },
    {
        "tag": "GPSImgDirection",
        "name": "GPS Image Direction",
        "description": "Direction of image when captured.",
        "multi_valued": False,
    },
    {
        "tag": "GPSDateStamp",
        "name": "GPS Date",
        "description": "GPS date (YYYY:MM:DD).",
        "multi_valued": False,
    },
    {
        "tag": "GPSTimeStamp",
        "name": "GPS Time",
        "description": "GPS time (HH:MM:SS).",
        "multi_valued": False,
    },
]

exif_writable_fields_list = [t["tag"] for t in exif_writable_tags]

